### ISSUE TITLE
how to download datasets

### ISSUE THREAD

**Issue by czkya** [morningD/FlexCFL#1]
Excuse me. I want to ask you how to download the dataset. It can't be downloaded in the way of fedProx.

**Comment by morningD** [comment]
Hi, the download links of [FedProx](https://github.com/litian96/FedProx/tree/master/data) and [Ditto](https://github.com/litian96/ditto/tree/master/data) are valid, I guess you need a scientific internet proxy to access Google Drive from mainland.
