### ISSUE TITLE
Question in script client.py

### ISSUE THREAD

**Issue by ghost** [morningD/FlexCFL#2]
Line 77 in client.py，function  _**train**_ return   acc  is the training accuracy of last local epoch, and  loss  is the  mean training loss of last local epoch
But why is return **_acc[0]_**, **_loss[0]_**, i think the acc[0], loss[0] is the training accuracy and loss of first local epoch.

**Comment by morningD** [comment]
Thank you for pointing that out. You're correct; I adjusted the return variables from the last epoch to the first epoch to showcase a complete trend of acc and loss (You can imagine that it represents the acc and loss of the last local epoch of the last communication epoch). I forgot to update the comments text, but the code still functions properly.
