### ISSUE TITLE
Question in computational complexity of similarity calculation in the paper

### ISSUE THREAD

**Issue by TaiyakiOffical** [morningD/FlexCFL#3]
if the cosine similarity computational complexity is O(n), how can we get the result below in the paper? maybe I have some wrong understanding, waiting for your answer!!
![Snipaste_2024-11-05_16-44-11](https://github.com/user-attachments/assets/bc57ea1b-602c-4b96-b3d9-e20734d27e7e)

**Comment by morningD** [comment]
n represent the number of clients. The computational complexity for calculating cosine similarity in this paper is O(dw^2), and n*n pairwise similarities need to be calculated.

**Comment by TaiyakiOffical** [comment]
> n represent the number of clients. The computational complexity for calculating cosine similarity in this paper is O(dw^2), and n*n pairwise similarities need to be calculated.

thanks for your answer, but how the computational complexity for the cosine similarity can be O(dw^2), if we compute the dot product of the two vectors(dw) and calculate the magnitude of each vector and divide former by latter?

**Comment by morningD** [comment]
> > n represent the number of clients. The computational complexity for calculating cosine similarity in this paper is O(dw^2), and n*n pairwise similarities need to be calculated.
> 
> thanks for your answer, but how the computational complexity for the cosine similarity can be O(dw^2), if we compute the dot product of the two vectors(dw) and calculate the magnitude of each vector and divide former by latter?

Yes, you’re right, it should be O(n^2*d_w). Thank you for the correction!
